spring.application.name=eduflow-auth-service
jwt.secret=eduflow-secret-key-eduflow-secret-key
spring.datasource.url=jdbc:postgresql://localhost:5432/eduflow_auth_db
spring.datasource.username=jagadish
spring.datasource.password=

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

server.port=8081